services:
  smtp2telegram:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smtp2telegram
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "2525:2525"

    read_only: true

    tmpfs:
      - /tmp

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - ALL

    secrets:
      - smtp_tls_cert
      - smtp_tls_key
      - zitadel_pkey

    environment:
      SMTP_TLS_CERT_FILE: /run/secrets/smtp_tls_cert
      SMTP_TLS_KEY_FILE: /run/secrets/smtp_tls_key
      # ZITADEL_PKEY_FILE: /run/secrets/zitadel_pkey


secrets:
  smtp_tls_cert:
    file: ./certs/smtp.crt

  smtp_tls_key:
    file: ./certs/smtp.key

  # если нужен ZITADEL:
  # zitadel_pkey:
  #   file: ./pkey.json